<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommandLineParser.FSharp" Version="2.9.1" />
    <PackageVersion Include="FFMpegCore" Version="5.4.0" />
    <PackageVersion Include="FSharp.Core" Version="10.0.101" />
    <PackageVersion Include="Instances" Version="3.0.2" />
    <PackageVersion Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>
</Project>